export default {
    HOME: 'Home',
    RIDDLE: 'Riddle',
    EASY: 'Easy',
    FUNNY: 'Funny',
    MATH: 'Math',
    WORD: 'Word',
    HARD: 'Hard',
    RANDOM: 'Random',

    BUGTONG: 'Bugtong',
    MADALI: 'Madali',
    NAKAKATAWA: 'Nakakatawa',
    MATEMATIKA: 'Matematika',
    SALITA: 'Salita',
    MAHIRAP: 'Mahirap',
    RANDOMTAGALOG: 'Random_tagalog',

    HANGMAN: 'Hangman',
    HANGMANLEVEL: 'HangmanLevel',
    LEVEL2: 'Level2',
    LEVEL3: 'Level3',
    LEVEL4: 'Level4',
    LEVEL5: 'Level5',
    LEVEL6: 'Level6',
    LEVEL7: 'Level7',
    LEVEL8: 'Level8',
    LEVEL9: 'Level9',
    LEVEL10: 'Level10',
    LEVEL11: 'Level11',
    LEVEL12: 'Level12',
    STATUSPOPUP: 'StatusPopUp',
};